name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install opencv-python-headless numpy
    
    - name: Run tests
      
      run: |
        pytest -v --tb=short
      continue-on-error: false

  build:
    name: Deploy SAM Application
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    #needs: test

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install AWS SAM CLI
      uses: aws-actions/setup-sam@v2
    
    - name: SAM Build
      run: sam build
      continue-on-error: true

    - name: Deploy SAM stack
      run: |
        sam deploy \
          --stack-name fiapx-video-processing \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset

